import { MigrationInterface, QueryRunner, Table, TableIndex } from 'typeorm';

/**
 * First production schema, hand-written against the 8 entities under `src/*\/entities` rather
 * than generated by `migration:generate` — there's no existing SQL Server reachable from this
 * dev machine to diff against (see the session's Docker/WSL2 investigation), and for a truly
 * initial migration a diff against an empty database and a from-scratch CREATE TABLE script are
 * the same thing anyway. Column types/defaults follow TypeORM's own mssql driver conventions
 * (SqlServerDriver.normalizeType/normalizeDefault): bare string columns -> nvarchar(255), enum-like
 * columns declared with an explicit `type: 'varchar'` -> varchar(255), booleans -> bit (1/0).
 *
 * Three self-referencing foreign-key pairs (activities.responsibleId/coResponsibleId -> users;
 * activity_dependencies' two columns -> activities; activity_template_dependencies' two columns
 * -> activity_templates) each had BOTH sides cascading in the original entity decorators. SQL
 * Server rejects that outright ("may cause cycles or multiple cascade paths", error 1785) — SQLite
 * never enforced it, so it went unnoticed in dev. One side of each pair is `NO ACTION` here (and
 * now in the entity decorators too, so a future `migration:generate` won't try to "fix" it back).
 * Harmless in practice: none of the three affected delete paths (users, activities,
 * activity_templates) has a DELETE endpoint today, so no cascade behavior is actually lost.
 */
export class InitialSchema1786989414004 implements MigrationInterface {
  name = 'InitialSchema1786989414004';

  public async up(queryRunner: QueryRunner): Promise<void> {
    await queryRunner.createTable(
      new Table({
        name: 'users',
        columns: [
          { name: 'id', type: 'int', isPrimary: true, isGenerated: true, generationStrategy: 'increment' },
          { name: 'name', type: 'nvarchar', length: '255' },
          { name: 'email', type: 'nvarchar', length: '255', isUnique: true },
          { name: 'passwordHash', type: 'nvarchar', length: '255' },
          { name: 'role', type: 'varchar', length: '255', default: "'MEMBER'" },
          { name: 'isActive', type: 'bit', default: 1 },
          { name: 'isVerified', type: 'bit', default: 0 },
          { name: 'verificationToken', type: 'varchar', length: '255', isNullable: true },
          { name: 'verificationTokenExpiresAt', type: 'datetime', isNullable: true },
          { name: 'passwordResetToken', type: 'varchar', length: '255', isNullable: true },
          { name: 'passwordResetTokenExpiresAt', type: 'datetime', isNullable: true },
          { name: 'pendingEmail', type: 'varchar', length: '255', isNullable: true },
          { name: 'emailChangeToken', type: 'varchar', length: '255', isNullable: true },
          { name: 'emailChangeTokenExpiresAt', type: 'datetime', isNullable: true },
        ],
      }),
      true,
    );
    await queryRunner.createIndex(
      'users',
      new TableIndex({ name: 'IDX_users_verificationToken', columnNames: ['verificationToken'] }),
    );
    await queryRunner.createIndex(
      'users',
      new TableIndex({ name: 'IDX_users_passwordResetToken', columnNames: ['passwordResetToken'] }),
    );
    await queryRunner.createIndex(
      'users',
      new TableIndex({ name: 'IDX_users_emailChangeToken', columnNames: ['emailChangeToken'] }),
    );

    await queryRunner.createTable(
      new Table({
        name: 'projects',
        columns: [
          { name: 'id', type: 'int', isPrimary: true, isGenerated: true, generationStrategy: 'increment' },
          { name: 'name', type: 'nvarchar', length: '255' },
          { name: 'description', type: 'text', isNullable: true },
          { name: 'status', type: 'varchar', length: '255', default: "'ACTIVE'" },
          { name: 'ownerId', type: 'int', isNullable: true },
          { name: 'startDate', type: 'date', isNullable: true },
          { name: 'endDate', type: 'date', isNullable: true },
        ],
      }),
      true,
    );

    await queryRunner.createTable(
      new Table({
        name: 'activity_templates',
        columns: [
          { name: 'id', type: 'int', isPrimary: true, isGenerated: true, generationStrategy: 'increment' },
          { name: 'title', type: 'nvarchar', length: '255' },
          { name: 'description', type: 'text', isNullable: true },
          { name: 'responsibleId', type: 'int', isNullable: true },
          { name: 'priority', type: 'varchar', length: '255', default: "'MEDIUM'" },
          { name: 'businessDayOffset', type: 'int' },
          { name: 'dueTime', type: 'varchar', length: '255', isNullable: true },
          { name: 'estimatedHours', type: 'float', isNullable: true },
          { name: 'notes', type: 'text', isNullable: true },
          { name: 'isActive', type: 'bit', default: 1 },
        ],
        foreignKeys: [
          {
            columnNames: ['responsibleId'],
            referencedTableName: 'users',
            referencedColumnNames: ['id'],
            onDelete: 'SET NULL',
          },
        ],
      }),
      true,
    );

    await queryRunner.createTable(
      new Table({
        name: 'activity_template_dependencies',
        columns: [
          { name: 'id', type: 'int', isPrimary: true, isGenerated: true, generationStrategy: 'increment' },
          { name: 'templateId', type: 'int' },
          { name: 'dependsOnTemplateId', type: 'int' },
        ],
        uniques: [{ name: 'UQ_activity_template_dependencies', columnNames: ['templateId', 'dependsOnTemplateId'] }],
        foreignKeys: [
          {
            columnNames: ['templateId'],
            referencedTableName: 'activity_templates',
            referencedColumnNames: ['id'],
            onDelete: 'CASCADE',
          },
          {
            // NO ACTION, not CASCADE — see class doc comment (SQL Server multi-cascade-path rule).
            columnNames: ['dependsOnTemplateId'],
            referencedTableName: 'activity_templates',
            referencedColumnNames: ['id'],
            onDelete: 'NO ACTION',
          },
        ],
      }),
      true,
    );

    await queryRunner.createTable(
      new Table({
        name: 'activities',
        columns: [
          { name: 'id', type: 'int', isPrimary: true, isGenerated: true, generationStrategy: 'increment' },
          { name: 'projectId', type: 'int' },
          { name: 'title', type: 'nvarchar', length: '255' },
          { name: 'description', type: 'text', isNullable: true },
          { name: 'responsibleId', type: 'int', isNullable: true },
          { name: 'coResponsibleId', type: 'int', isNullable: true },
          { name: 'priority', type: 'varchar', length: '255', default: "'MEDIUM'" },
          { name: 'status', type: 'varchar', length: '255', default: "'TO_DO'" },
          { name: 'startDate', type: 'datetime', isNullable: true },
          { name: 'deadline', type: 'datetime', isNullable: true },
          { name: 'businessDayOffset', type: 'int', isNullable: true },
          { name: 'dueDateRuleMonth', type: 'int', isNullable: true },
          { name: 'dueDateRuleYear', type: 'int', isNullable: true },
          { name: 'dueTime', type: 'varchar', length: '255', isNullable: true },
          { name: 'templateId', type: 'int', isNullable: true },
          { name: 'completionDate', type: 'datetime', isNullable: true },
          { name: 'progressPercent', type: 'int', default: 0 },
          { name: 'estimatedHours', type: 'float', isNullable: true },
          { name: 'actualHours', type: 'float', isNullable: true },
          { name: 'exceededHours', type: 'float', default: 0 },
          { name: 'notes', type: 'text', isNullable: true },
          { name: 'createdAt', type: 'datetime', default: 'getdate()' },
        ],
        foreignKeys: [
          {
            columnNames: ['projectId'],
            referencedTableName: 'projects',
            referencedColumnNames: ['id'],
            onDelete: 'CASCADE',
          },
          {
            columnNames: ['responsibleId'],
            referencedTableName: 'users',
            referencedColumnNames: ['id'],
            onDelete: 'SET NULL',
          },
          {
            // NO ACTION, not SET NULL — see class doc comment (SQL Server multi-cascade-path rule).
            columnNames: ['coResponsibleId'],
            referencedTableName: 'users',
            referencedColumnNames: ['id'],
            onDelete: 'NO ACTION',
          },
          {
            columnNames: ['templateId'],
            referencedTableName: 'activity_templates',
            referencedColumnNames: ['id'],
            onDelete: 'SET NULL',
          },
        ],
      }),
      true,
    );

    await queryRunner.createTable(
      new Table({
        name: 'activity_dependencies',
        columns: [
          { name: 'id', type: 'int', isPrimary: true, isGenerated: true, generationStrategy: 'increment' },
          { name: 'activityId', type: 'int' },
          { name: 'dependsOnActivityId', type: 'int' },
        ],
        uniques: [{ name: 'UQ_activity_dependencies', columnNames: ['activityId', 'dependsOnActivityId'] }],
        foreignKeys: [
          {
            columnNames: ['activityId'],
            referencedTableName: 'activities',
            referencedColumnNames: ['id'],
            onDelete: 'CASCADE',
          },
          {
            // NO ACTION, not CASCADE — see class doc comment (SQL Server multi-cascade-path rule).
            columnNames: ['dependsOnActivityId'],
            referencedTableName: 'activities',
            referencedColumnNames: ['id'],
            onDelete: 'NO ACTION',
          },
        ],
      }),
      true,
    );

    await queryRunner.createTable(
      new Table({
        name: 'activity_history',
        columns: [
          { name: 'id', type: 'int', isPrimary: true, isGenerated: true, generationStrategy: 'increment' },
          { name: 'activityId', type: 'int' },
          { name: 'eventType', type: 'varchar', length: '255' },
          { name: 'oldValue', type: 'text', isNullable: true },
          { name: 'newValue', type: 'text', isNullable: true },
          { name: 'changedById', type: 'int', isNullable: true },
          { name: 'occurredAt', type: 'datetime', default: 'getdate()' },
        ],
        foreignKeys: [
          {
            columnNames: ['activityId'],
            referencedTableName: 'activities',
            referencedColumnNames: ['id'],
            onDelete: 'CASCADE',
          },
          {
            columnNames: ['changedById'],
            referencedTableName: 'users',
            referencedColumnNames: ['id'],
            onDelete: 'SET NULL',
          },
        ],
      }),
      true,
    );

    await queryRunner.createTable(
      new Table({
        name: 'notification_logs',
        columns: [
          { name: 'id', type: 'int', isPrimary: true, isGenerated: true, generationStrategy: 'increment' },
          { name: 'type', type: 'varchar', length: '255' },
          { name: 'channel', type: 'varchar', length: '255' },
          { name: 'recipientId', type: 'int' },
          { name: 'activityId', type: 'int' },
          { name: 'subject', type: 'nvarchar', length: '255' },
          { name: 'body', type: 'text' },
          { name: 'status', type: 'varchar', length: '255' },
          { name: 'sentAt', type: 'datetime', default: 'getdate()' },
        ],
      }),
      true,
    );
  }

  public async down(queryRunner: QueryRunner): Promise<void> {
    // Reverse creation order — children before parents.
    await queryRunner.dropTable('notification_logs');
    await queryRunner.dropTable('activity_history');
    await queryRunner.dropTable('activity_dependencies');
    await queryRunner.dropTable('activities');
    await queryRunner.dropTable('activity_template_dependencies');
    await queryRunner.dropTable('activity_templates');
    await queryRunner.dropTable('projects');
    await queryRunner.dropTable('users');
  }
}
