export enum ActivityHistoryEventType {
  CREATED = 'CREATED',
  STARTED = 'STARTED',
  ASSIGNEE_CHANGED = 'ASSIGNEE_CHANGED',
  STATUS_CHANGED = 'STATUS_CHANGED',
  BECAME_LATE = 'BECAME_LATE',
  DEPENDENCY_RESOLVED = 'DEPENDENCY_RESOLVED',
  COMPLETED = 'COMPLETED',
}
